# Parametros para nodos o modelos en models ==================================
numero_nodos: 12 # Cantidad de modelos : xgboost, rf , # cuantos modelos quiero correr 
muestreos: [7 , 7, 7, 6, 6, 6, 8,8,8,9,9,9] # experimento 1
#muestreos: [1 , 1, 1, 2, 2, 2, 4,4,4,5,5,5] # experimento 2
#muestreos: [10, 10, 10, 11, 11, 11, 3, 3, 3, 12, 12, 12] # experimento 3
#muestreos: [13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16] # experimento 4

names: ["Run0","Run1","Run2","Run3","Run4","Run5","Run6","Run7","Run8","Run9","Run10","Run11"] #"Run4" el numero esta asociado al nodo 

# analisis de metricas: ==================================
plot:
  desea_plot: False
  grilla: ['max_depth','n_estimators','hidden_layer_sizes','activation'] #,'scale_pos_weight','class_weight','alpha'
# tratamiento de nulos en Y ==================================
y_method: 'drop' # 'drop','fillna'
y_method_value: 0 # if fillna 

# First train model ==================================  
xgboost:
  class_weight: True # Ratio de Muestras: Clase 0 / Clase 1 (incluir a la grilla el castigo segun el balanceo)
  param_grid:
    max_depth: [3, 5, 10]
    learning_rate: [0.01, 0.1, 0.3]
    scale_pos_weight: [1,10,100] #Ratio de Muestras: Clase 0 / Clase 
    n_estimators: [100,400,900] # numero de arboles
  cv_params:
    n_splits: 5 # k folds
    scoring: 'f1'
    n_jobs: -1

# Parametros para elpupeline de modelos 

random_forest:
  class_weight: True # calcula el ratio de y y lo mete en la gruilla segun el tipo de balanceo # Ratio de Muestras: Clase 0 / Clase 1 #mirar
  param_grid:
    n_estimators: [100, 450,900] # numero de arboles
    class_weight: [{0.0: 1, 1.0: 1},{0.0: 1, 1.0: 10},{0.0: 1, 1.0: 100}]
    max_depth: [3, 5, 10]
    min_samples_split: [0.02,0.05,0.08] # porcentaje 
    min_samples_leaf: [1, 2, 4] # ultimo nodo 
    max_features: ['sqrt']
  cv_params:
    n_splits: 5 # k folds
    scoring: 'f1'
    n_jobs: -1
    n_iter: 5

MLP:
  class_weight: True # incluir el regulador en alpha de forma outomatica (Ratio de Muestras: Clase 0 / Clase 1)
  max_iter: 500 # epochs
  param_grid: {
        'hidden_layer_sizes_1': [[1],[100],[10], [20]],
        'hidden_layer_sizes_2': [[10, 5], [20, 10]],
        'hidden_layer_sizes_3': [[]],
        'hidden_layer_sizes_4': [[]],
        'activation': ['tanh','logistic', 'relu'],
        'solver': ['adam', 'sgd'],
        'alpha': [0.0001, 0.001, 0.01, 1.0]}
  cv_params:
    n_splits: 5 # k folds
    scoring: 'f1'
    n_jobs: -1

compare_metrics_models:
    # ideal tomar train si se quiere reoptimizar en model_select  
    dataset_name: 'test' # se puede escoger el mejor modelo segun el mejor 'train', 'test' 
    # solo puede ser una 
    metric_name: 'f1-score'  
    # clase o producto a analizar
    class_name: ['1','1.0',1, 1.0]

# Parámetros para balancear
balance_target_variable: {
    'Y_nulos': 'drop', # 'drop', 'fill_0'
    # 'Segmento': 3, # segmento asociado a la llave de muestreo que se quiera realizar
    'random_state': 42,
    #"Smote", "Undersampling", "Undersampling-Smote", "Smote-Undersampling", "Oversampling", "ADASYN","Undersampling-Oversampling", "Undersampling-ADASYN"
    'Muestreo': {1:{
                    ## Grupo 1
                    "Type":"Undersampling-Oversampling", 
                    "sampling_strategy_osc": 0.45, # la clase minorista tiene x% del tamaño del clase mayorista
                    "sampling_strategy_osc2": 1,
                    "Use_auto":False},  # True implica modelo perfectamente balancedado
                2:{
                    ## Grupo 2
                    "Type":"Undersampling", 
                    "sampling_strategy_osc": 0.95, 
                    "sampling_strategy_osc2": 0.7,
                    "Use_auto":False},
                3:{
                   ## Grupo 3
                    "Type":"Undersampling-Smote",
                    "sampling_strategy_osc": 0.7,
                    "sampling_strategy_osc2": 0.9,
                    "Use_auto":False},
                4:{
                   ## Grupo 4
                    "Type":"Undersampling-Smote",
                    "sampling_strategy_osc": 0.6,
                    "sampling_strategy_osc2": 1,
                    "Use_auto":True},
                5:{
                    ## Grupo 5
                    "Type":"Undersampling-Oversampling", 
                    "sampling_strategy_osc": 0.5, 
                    "sampling_strategy_osc2": 0.95,
                    "Use_auto":False},
                6:{
                    ## Grupo 6
                    "Type":"Undersampling", 
                    "sampling_strategy_osc": 0.8, 
                    "sampling_strategy_osc2": 0.5,
                    "Use_auto":False},
                7:{
                    ## Grupo 7
                    "Type":"Undersampling-Oversampling", 
                    "sampling_strategy_osc": 0.62, 
                    "sampling_strategy_osc2": 0.65,
                    "Use_auto":False},
                8:{
                    ## Grupo 8
                    "Type":"Undersampling-Smote", 
                    "sampling_strategy_osc": 0.62, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.8, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                9:{
                    ## Grupo 9
                    "Type":"Undersampling-Oversampling", 
                    "sampling_strategy_osc": 0.62, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.95, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                10:{
                    ## Grupo 10
                    "Type":"Undersampling-Smote", 
                    "sampling_strategy_osc": 0.40, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.7, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                11:{
                    ## Grupo 11
                    "Type":"Undersampling", 
                    "sampling_strategy_osc": 0.40, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.95, 
                    "Use_auto":False},
                12:{
                    ## Grupo 12
                    "Type":"Undersampling", 
                    "sampling_strategy_osc": 0.7, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.95, 
                    "Use_auto":False},
                13:{
                    ## Grupo 13
                    "Type":"Undersampling-ADASYN", 
                    "sampling_strategy_osc": 0.40, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.7, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                14:{
                    ## Grupo 14
                    "Type":"Undersampling-ADASYN", 
                    "sampling_strategy_osc": 0.6, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.8, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                15:{
                    ## Grupo 15
                    "Type":"Undersampling-ADASYN", 
                    "sampling_strategy_osc": 0.7, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 0.9, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":False},
                16:{
                    ## Grupo 16
                    "Type":"Undersampling-ADASYN", 
                    "sampling_strategy_osc": 0.6, #Undersampling : la clase mayorista va a ser el doble de la minorista 
                    "sampling_strategy_osc2": 1, # oversampling : aumenta el numeor de la clase monoritaria respecto a la mayporitaria 
                    "Use_auto":True},
        }

}
